name: Apidog Test & Slack Alert

on:
  push:
    branches:
      - main

jobs:
  apitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # npm ì „ì—­ ìºì‹œ ì„¤ì •
      - name: Cache npm global packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Apidog CLI if not exists
        run: |
          if ! command -v apidog &> /dev/null
          then
            echo "Apidog CLI not found. Installing..."
            npm install -g apidog-cli@latest --loglevel=error
          else
            echo "Apidog CLI already installed. Skipping install."
          fi

      - name: Run Apidog Tests
        run: apidog run --access-token=${{ secrets.APIDOG_KEY }} -t 1447647 -e 4859894 -n 1 -r html,cli

      - name: Slack Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"ğŸš¨ Apidog í…ŒìŠ¤íŠ¸ ì‹¤íŒ¨! í™•ì¸í•´ì£¼ì„¸ìš”.\nğŸ”— í”„ë¡œì íŠ¸: https://apidog.com/project/1075390"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"âœ… Apidog í…ŒìŠ¤íŠ¸ ì„±ê³µ! ğŸ‰\nğŸ”— í”„ë¡œì íŠ¸: https://apidog.com/project/1075390"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
